### ISSUE TITLE
packed structures

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#339] opened 2018-12-19 15:32 UTC
SAW seems unable to deal with packed structs in bitcode.  I'm working with a file that does not ask for packing, but clang has added it, as can be seen in the bitcode:

    %struct.anon.3 = type <{ [2 x %struct.something_s], [2 x %struct.or_other_s] }>

where, as I recently learned, the "<{" "}>" brackets indicate packing.

A small example where I _do_ ask for packing exhibits the same failure.  The C code:

    #include <stdint.h>

    typedef struct  __attribute__((packed)) S { uint8_t y[3]; uint64_t z[2]; } S_t;

    void f(S_t *x) {
      return;
    }

the SAW

    m <- llvm_load_module "packed.bc";

    let S_t = llvm_struct "struct.S";

    let f_setup = do {
        y <- crucible_fresh_var "y" (llvm_array 3 (llvm_int 8));
        z <- crucible_fresh_var "z" (llvm_array 2 (llvm_int 64));
        let x = crucible_struct [crucible_term y, crucible_term z];
        p <- crucible_alloc S_t;
        crucible_points_to p x;
        crucible_execute_func [p];
        };

    crucible_llvm_verify m "f" [] false f_setup z3;

and the sad result (here in the December 13 nightly build, but in earlier versions too):

    $ saw packed.saw
    Loading file "packed.saw"
    user error ("crucible_llvm_verify" (packed.saw:17:1-17:21):
    "f_setup" (packed.saw:17:37-17:44):
    "crucible_points_to" (packed.saw:12:5-12:23):
    types not memory-compatible:
    { [3 x i8], [2 x i64] }
    { [3 x i8], [2 x i64] }
    )

If the packed attribute is removed, the proof succeeds.  Is there any remedy or work-around?

**Comment by brianhuffman** [comment] 2018-12-19 17:48
I expect the problem is that `crucible_struct` only produces values with non-packed struct types. We probably need to have a corresponding `crucible_packed_struct` operator.

It looks like there is another, separate problem here in the pretty-printer for llvm types. In the `types not memory-compatible` error message, I bet one of those two struct types is actually packed, but it's not printed with the appropriate `<{` `}>` brackets.

**Comment by brianhuffman** [comment] 2018-12-19 17:50
As a workaround, instead of 
```
    let x = crucible_struct [crucible_term y, crucible_term z];
    p <- crucible_alloc S_t;
    crucible_points_to p x;
```
you should be able to avoid `crucible_struct` by using `crucible_elem` instead:
```
    p <- crucible_alloc S_t;
    crucible_points_to (crucible_elem p 0) (crucible_term y);
    crucible_points_to (crucible_elem p 1) (crucible_term z);
```

**Comment by cchiw** [comment] 2018-12-19 18:13
Okay.  I tried adjusting the code for our actual example but had an issue (line 4).

```
1. y <- A_param "y" (llvm_array 2 r_s);
2. z <- A_param "z" (llvm_array 2 compressed_idx_dv_s);
3. p1 <- crucible_alloc sk_t;
4. crucible_points_to (crucible_elem p1 0) (crucible_term y);
5. crucible_points_to (crucible_elem p1 1) (crucible_term z);
```
Error
`types not memory-compatible:
{ { [2 x { [1271 x i8] }], [2 x { [133 x { i32, i32 }] }] } }
[2 x { [1271 x i8] }]
`

**Comment by cchiw** [comment] 2018-12-19 18:17
Also, our final type (sk_t) has more structs wrapped around the result. Would it be "right" to nest that pointer into a crucible structure.
`
1. let b = crucible_struct [p1];
2. let c = crucible_struct [b];
3. p2 <- crucible_alloc sk_t;
4. crucible_points_to p2 c;
`

**Comment by robdockins** [comment] 2018-12-19 19:23
The code that checks for memory compatibility of structs looks like this:

```
    (Crucible.StructType x, Crucible.StructType y)
      | Crucible.siIsPacked x == Crucible.siIsPacked y
        && V.length (Crucible.siFields x) == V.length (Crucible.siFields y) ->
          let xts = Crucible.siFieldTypes x
              yts = Crucible.siFieldTypes y
          in diffMemTypesList 1 (V.toList (V.zip xts yts))
```

So, a non-packed struct will not be compatible with a packed struct.  Probably, we should relax this so that two structs (packed or not) are memory-compatible iff they have the same starting offsets and types for corresponding fields and the same overall length.  This captures the case where an appropriately aligned non-packed struct happens to have the exact same memory layout as a packed struct.

In addition, we should add a setup value combinator for generating packed structs.

**Comment by brianhuffman** [comment] 2018-12-19 21:53
Wow, that's a lot of nested struct types. Instead of `crucible_elem p1 0` you might need to do something like `crucible_elem (crucible_elem (crucible_elem p1 0) 0) 0`.

**Comment by brianhuffman** [comment] 2018-12-19 22:46
Ok, in a2f95b901f0440597836be203ec15082222724ab we now have a `crucible_packed_struct` command. The example from the original post now works if `crucible_struct` is replaced with `crucible_packed_struct`.

Before closing this ticket we should also implement all the changes to the memory-compatibility test that @robdockins suggested.

**Comment by cchiw** [comment] 2018-12-20 00:48
Hi, could this new version of SAW have an error?
`at :330:5: Specified alignment: 1
  insufficent for type: Alias (Ident "struct.double_seed_s")`

The file just includes 
m <- llvm_load_module "..";

**Comment by cchiw** [comment] 2018-12-20 20:31
okay I did. #340

**Closed** 2019-01-03 00:11 UTC
