### ISSUE TITLE
Some integration tests not being run in CI

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#995] opened 2021-01-08 18:11 UTC
It appears the integration test suite is not being run in CI jobs, which allows errors like #994 to occur.

**Comment by RyanGlScott** [comment] 2021-01-08 18:15
CI _is_ running the integration tests—see [here](https://github.com/GaloisInc/saw-script/runs/1665661814?check_suite_focus=true#step:14:1). The issue is that CI is excluding certain tests, including `test_examples` (the subject of #994) [here](https://github.com/GaloisInc/saw-script/blob/898e663ab559f89d39fe4dc539f7edd07e917ea1/.github/ci.sh#L173).

**Comment by kquick** [comment] 2021-01-15 21:45
If test suite invoked SAW directly instead of as a sub-process, this might enable better coverage reporting.  Still probably need at least a couple of tests that invoke the executable to ensure that part works correctly.

**Comment by brianhuffman** [comment] 2021-01-18 14:59
I made this comment in #1013, but I thought I should repeat it here: This CI script contains a list of excluded tests.
https://github.com/GaloisInc/saw-script/blob/6789b1a44e5a4b3373e114ebb710ce9d7ecbddd1/.github/ci.sh#L173

It would be nice to add comments explaining why each of these tests is excluded, to make it easier to know if/when it is appropriate to add each one back in. And any test that is actually broken should have a ticket.

**Comment by brianhuffman** [comment] 2021-01-18 15:17
Just for historical context, here are the commits that introduced the lists of excluded tests: e905271ea205452d22179cd9cc881d547bfbd051, 4acafb38e6eb678f5f140f4356c62dad424804b7.

The file `intTests/disabled_tests.txt` actually does contain comments explaining why certain tests are excluded. It appears CI excludes the tests named in the CI scripts themselves in addition to the ones listed in this file.

**Comment by brianhuffman** [comment] 2021-02-15 00:52
As of #1070, `.github/ci.sh` no longer excludes any additional tests (besides those explicitly excluded in `intTests/disabled_tests.txt`). Is this sufficient to close this ticket?

**Comment by kquick** [comment] 2021-02-15 02:01
I believe it can, if @rdockins and @RyanGlScott don't have any objections.  Thanks @brianhuffman !

**Closed** 2021-02-15 04:45 UTC
Labels: priority, testing

**Comment by RyanGlScott** [comment] 2021-02-15 13:47
Sounds good to me. I agree with this part of #1070:

> If there is a specific reason for any integration test to be
> excluded from CI, the rationale for exclusion should be given
> in a comment inside `disabled_tests.txt`.
