### ISSUE TITLE
ECDSA Cryptol test vector is failing

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#218] opened 2017-07-27 19:09 UTC
In the `examples/ecdsa/cryptol-spec/ecc_tests.cry` file are a number of test vectors.  Currently the test involving the `test_p384_ds` value is failing.

I don't know if this represents a bug in the ECC specification or in the Cryptol interpreter.

**Comment by atomb** [comment] 2018-09-14 15:30
This is a duplicate of #305.

**Closed by atomb** 2018-09-14 15:30 UTC
