### ISSUE TITLE
tutorial5 integration test fails

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#559] opened 2019-10-03 00:36 UTC
the `test_tutorial5` integration test is broken and has been for some time

```
$SAW des3.saw
+ eval saw -j ''\''/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Users/rdockins/code/saw-script/intTests/jars/org.sat4j.core.jar:/Users/rdockins/code/saw-script/intTests/../deps/jvm-verifier/jars/bcprov-jdk16-145.jar:/Users/rdockins/code/saw-script/intTests/../deps/jvm-verifier/jars/galois.jar'\''' des3.saw
saw -j '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Users/rdockins/code/saw-script/intTests/jars/org.sat4j.core.jar:/Users/rdockins/code/saw-script/intTests/../deps/jvm-verifier/jars/bcprov-jdk16-145.jar:/Users/rdockins/code/saw-script/intTests/../deps/jvm-verifier/jars/galois.jar' des3.saw
++ saw -j /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Users/rdockins/code/saw-script/intTests/jars/org.sat4j.core.jar:/Users/rdockins/code/saw-script/intTests/../deps/jvm-verifier/jars/bcprov-jdk16-145.jar:/Users/rdockins/code/saw-script/intTests/../deps/jvm-verifier/jars/galois.jar des3.saw
[00:32:31.402] Loading file "/Users/rdockins/code/saw-script/intTests/test_tutorial5/tmp/des3.saw"
[warning] at ./DES.cry:25:9--25:13
    This binding for last shadows the existing binding from
    (at /var/folders/8p/2bcq61wj76q3mvgbk020zjg00000gp/T/Cryptol59593-0.cry:595:1--595:5, last)
[warning] at ./DES.cry:25:16--25:38:
  Defaulting type argument 'ix' of '(Cryptol::@)' to max 1
                                                         (width ?n`1068)
  where
  ?n`1068 is length of comprehension generator at ./DES.cry:22:15--24:35
[00:32:31.523] proving dec_enc...
[00:32:34.999] Valid
[00:32:34.999] proving enc_dec...
[00:32:38.844] Valid
[00:32:38.844] Theorem (let { x@1 = Prelude.Vec 64 Prelude.Bool
    }
 in (key : x@1)
-> (msg : x@1)
-> Prelude.EqTrue (prop2 key msg))
[00:32:38.873] proving dec3_enc3...
[00:32:38.902] ruleOfProp: Predicate not an equation: prop1 !1 !0
CallStack (from HasCallStack):
  error, called at src/Verifier/SAW/Rewriter.hs:306:16 in saw-core-0.1-AjbnSWeJN8N1F4i7YxIYAV:Verifier.SAW.Rewriter
```

**Comment by brianhuffman** [comment] 2019-10-03 15:26
Duplicate of #511.

**Closed** 2019-10-03 15:26 UTC
