### ISSUE TITLE
SAW should look for files relative to the SAW file being processed

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/saw-script#78] opened 2015-12-02 21:16 UTC
Currently, if I have a setup like this:
```
$ ls
main.saw	subdir
$ ls subdir/
sub.saw		sub2.saw
$ cat main.saw 
include "subdir/sub.saw";
$ cat subdir/sub.saw 
include "sub2.saw";
$ cat subdir/sub2.saw 
// Do stuff
```
And I try to run saw on `main.saw`, I get an error:
```
$ saw main.saw 
Loading module Cryptol
Loading file "main.saw"
Loading file "subdir/sub.saw"
Loading file "sub2.saw"
saw: sub2.saw: openFile: does not exist (No such file or directory)
```
It would be better if `sub.saw` was able to `include` files relative to its location.

The same issue exists when using `read_core` and possibly elsewhere.

**Comment by brianhuffman** [comment] 2016-05-23 17:02
Duplicate of #17.

**Closed by brianhuffman** 2016-05-23 17:02 UTC
Labels: easy
